name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Service File
        run: sudo scp -v -o StrictHostKeyChecking=no -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") $GITHUB_WORKSPACE/test-api.service ec2-user@ec2-3-253-33-5.eu-west-1.compute.amazonaws.com:/etc/systemd/system/

      - name: Deploy to EC2
        run: |
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") ec2-user@ec2-3-253-33-5.eu-west-1.compute.amazonaws.com 'cd test-api && git pull && npm install && pm2 restart test-api'
          echo "Deployment completed."
